name: flutter_demo
description: A Flutter demo project for Clerk package.
publish_to: none
version: 1.0.0
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  clerk:
    version: ^0.3.0
    path: ../../../
  demo_core:
    version: ^1.0.0
    path: ../demo_core
  flutter:
    sdk: flutter
  summon:
    version: ^0.1.0
    git: git@github.com:dmitryelagin/summon.git
dev_dependencies:
  pedantic: ^1.9.0
flutter:
  uses-material-design: true
