name: clerk
version: 0.3.16
description: >-
  Command-based state manager. Clerk can properly compose small
  logic parts to improve readability and reusability of state
  management in your project.
environment:
  sdk: '>=2.9.0-14.0.dev <3.0.0'
dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
  test: ^1.14.7
