name: clerk
version: 0.4.0
description: >-
  A command-based state manager. Clerk can properly compose small
  logic parts to improve readability and reusability of state
  management in your project.
environment:
  sdk: '>=2.9.0 <3.0.0'
dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
